# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='belt_review.Book'),
        ),
    ]
