# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='revew',
            new_name='review',
        ),
    ]
